var PrototypeUnitSchema = new Schema({
	_id:Number,
	name:String,
	primary_attribute:String,
	strength:Number,
	dexterity:Number,
	intelligence:Number,
	vitality:Number,
	sprite:String,
	portrait:String,
	index:Number,
	level:Number,
	exp:Number,
	resource_type:String,
	movement_speed:Number,
	critical_rate:Number,
	critical_damage:Number,
	radius:Number,
	aggro_radius:Number,
	range:Number,
	type:String,
	team:String,
	health_color:String,
	damage_color:String,
	regX:Number,
	regY:Number,
	recruitable:Boolean,
	_items:[{type:Schema.Types.ObjectId, ref:'Item'}],
	_skills:[{type:Schema.Types.ObjectId, ref:'Skill'}]
});

PrototypeUnitModel = mongoose.model('PrototypeUnit', PrototypeUnitSchema);