var UnitSchema = new Schema({
	name:String,
	primary_attribute:String,
	strength:Number,
	dexterity:Number,
	intelligence:Number,
	vitality:Number,
	sprite:String,
	portrait:String,
	index:Number,
	rate:Number,
	level:Number,
	exp:Number,
	resource_type:String,
	movement_speed:Number,
	critical_rate:Number,
	critical_damage:Number,
	radius:Number,
	aggro_radius:Number,
	range:Number,
	type:String,
	team:String,
	health_color:String,
	damage_color:String,
	_user:{type:Schema.Types.ObjectId, ref:'User'},
	_items:[{type:Schema.Types.ObjectId, ref:'Item'}],
	_skills:[{type:Schema.Types.ObjectId, ref:'Skill'}]
});

UnitModel = mongoose.model('Unit', UnitSchema);