var UnitSchema = new Schema({
	name:String,
	src:String,
	portrait_src:String,
	index:Number,
	rate:Number,
	level:Number,
	exp:Number,
	resource_type:String,
	resource:Number,
	max_resource:Number,
	health:Number,
	damage:Number,
	attack_speed:Number,
	armor:Number,
	movement_speed:Number,
	critical_rate:Number,
	critical_damage:Number,
	radius:Number,
	aggro_radius:Number,
	range:Number,
	type:String,
	team:String,
	health_color:String,
	damage_color:String,
	_user:{
		type:Schema.Types.ObjectId,
		ref:'User'
	},
	_items:[{
		type:Schema.Types.ObjectId,
		ref:'Item'
	}],
	_skills:[{
		type:Schema.Types.ObjectId,
		ref:'Skill'
	}]
});

UnitModel = mongoose.model('Unit', UnitSchema);