var WeaponSchema = new Schema({
	primary_attribute:Number,
	part:{type:String, default:"weapon"},
	hand:Number,
	type:String,
	attack_type:String,
	name:String,
	min_damage:Number,
	max_damage:Number,
	attack_speed:Number,
	range:Number,
	sprite:{
		source:String,
		cropX:Number,
		cropY:Number,
		width:Number,
		height:Number,
		regX:Number,
		regY:Number,
		scale:Number,
	},
	projectile:{
		source:String,
		cropX:Number,
		cropY:Number,
		width:Number,
		height:Number,
		regX:Number,
		regY:Number,
		scale:Number,
		spin:Number,
	},
	attributes:Schema.Types.Mixed,
}, { versionKey: false });

WeaponModel = mongoose.model('Weapon', WeaponSchema);